# Generated by Django 3.0.7 on 2021-02-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210211_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, unique=True, unique_for_date=True),
        ),
    ]
