# Generated by Django 3.0.7 on 2021-02-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210211_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=1500, unique_for_date=True),
        ),
    ]
