# Generated by Django 3.0.7 on 2021-02-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210210_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmassage',
            old_name='massage',
            new_name='message',
        ),
    ]
